@startuml Zustandsdiagramm
' Preview durch <Alt>d

hide empty description

state AuthProvider {
  AuthProvider : token
  AuthProvider : writeAccess
}

state App {
  [*] --> Home

  state Home {
    [*] --> Main
    Main -down-> Search : Button "Suche"
    Main -down-> NewBook : Button "Neues Buch" [wenn eingeloggt]
    Main -down-> DiagramSelection : Button "Diagramme"
  }

  state Search {
    [*] --> SearchForm : Suchkriterien eingeben
    SearchForm --> Waiting : Button "Suche"
    Waiting --> BookTable : Suchergebnis eingetroffen


    state BookTable {
      [*] --> GefundeneBuecher : mind. 1 passendes Buch gefunden
      GefundeneBuecher --> BookDetail : Zeile auswählen
    }
  }

  state BookDetail {
    [*] --> Details
    Details --> Edit : Button "Bearbeiten" [wenn eingeloggt]
    Details --> Delete : Button "Löschen" [wenn eingeloggt]
  }

  state Edit {
    [*] --> DataFields : Änderungen eintragen
    state UpdateChoice <<choice>>
    DataFields --> UpdateChoice : Button "Speichern"
    UpdateChoice --> UpdateBook : valide Daten
    UpdateChoice --> UpdateFehlermeldung : fehlerhafte Daten
    UpdateBook --> Edit : Daten hochladen
    UpdateFehlermeldung --> DataFields : Daten abändern
  }

  state NewBook {
    [*] --> InputFields : Daten eines neuen Buches eintragen
    state AddChoice <<choice>>
    InputFields --> AddChoice : Button "Ok"
    AddChoice --> CreateBook : valide Daten
    AddChoice --> CreateFehlermeldung : invalide Daten
    CreateBook --> BookDetail : Buch wird hochgeladen und Detailansicht anzeigen
    CreateFehlermeldung --> InputFields : Daten abändern
  }

  state DiagramSelection {
    [*] --> BarChart : Button "Balkendiagramm"
    [*] --> PieChart : Button "Kuchendiagramm"
  }

  state NotFound {
    [*] --> NotFound : ungültiger Pfad
  }

  state Forbidden {
    [*] --> Forbidden : kein Zugriff
  }

  Home --> Forbidden : kein Zugriff
  Home --> NotFound : ungültiger Pfad
}

@enduml
