name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    services:
      # Start a web server for your application
      web:
        image: nginx:latest
        ports:
          - 4200:80
        options: >-
          --mount type=bind,source=${{ github.workspace }}/,target=/usr/share/nginx/html
          
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress tests
      uses: cypress-io/github-action@v5
      with:
        start: npm start
        wait-on: http://localhost:4200
        wait-on-timeout: 120
      env:
        CI: true
